[package]
name = "slang-cli-rs"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]

[build-dependencies]
curl = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
zip = "2"